# Generated by Django 3.0.4 on 2020-04-04 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2020, 4, 4, 19, 11, 41, 506863, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
    ]
