# Generated by Django 3.0.4 on 2020-04-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
